version: "3.8"
name: mfl-assistant_prod

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file: mongodb.prod.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_DATABASE: mfl-assistant
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - /var/www/mfl-assistant/database/data:/data

  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: mfl-assistant.com
    env_file: mail-server.prod.env
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - /var/www/mfl-assistant/mail/dms/mail-data/:/var/mail/
      - /var/www/mfl-assistant/mail/dms/mail-state/:/var/mail-state/
      - /var/www/mfl-assistant/mail/dms/mail-logs/:/var/log/mail/
      - /var/www/mfl-assistant/mail/dms/config/:/tmp/docker-mailserver/
      - /var/www/mfl-assistant/mail/letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

  certbot:
    image: certbot/certbot
    container_name: certbot
    ports:
      - "80:80"
    volumes: 
      - /var/www/mfl-assistant/mail/letsencrypt:/etc/letsencrypt
      - /var/www/mfl-assistant/certbot/logs:/var/log/letsencrypt/
    command: certonly --standalone --force-renewal --email team@mfl-assistant.com -d mail.mfl-assistant.com --agree-tos

  api:
    image: mfl-assistant_api:local
    container_name: api
    build:
      context: ../api
      dockerfile: Dockerfile
    env_file: api.prod.env
    environment:
      ORIGINS: "https://mfl-assistant.com,https://www.mfl-assistant.com"
      HOST: "https://api.mfl-assistant.com/"
      WEBAPP_ENDPOINT: "https://mfl-assistant.com"
      DB_HOSTNAME: "mongodb"
      DB_NAME: "mfl-assistant"
      DB_USERNAME: "root"
      DB_PORT: "27017"
      DB_DRIVER: "mongodb"
      MAIL_SERVER: "mail.mfl-assistant.com"
      MAIL_USERNAME: "team@mfl-assistant.com"
      MAIL_PORT: "465"
      MAIL_FROM: "team@mfl-assistant.com"
      MAIL_FROM_NAME: "MFL Assistant"
      MAIL_STARTTLS: false
      MAIL_SSL_TLS: true
      USE_CREDENTIALS: true
      VALIDATE_CERTS: true
      MAIL_DEBUG: 1
    ports:
      - "5000:5000"
    expose:
      - "5000"
    depends_on:
      - mongodb
      - mailserver

  web:
    image: mfl-assistant_web:local
    container_name: web
    build:
      context: ../web
      dockerfile: Dockerfile.prod
      target: production
    ports:
      - "3000:80"

networks:
  default:
    name: mfl-assistant