version: "3.8"
name: mfl-assistant_dev

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mfl-assistant
    ports:
      - "27017:27017"
    expose:
      - "27017"

  api:
    image: mfl-assistant_api:local
    build:
      context: ../api
      dockerfile: Dockerfile
    environment:
      DB_HOSTNAME: "mongodb"
      DB_NAME: "mfl-assistant"
      DB_USERNAME: "root"
      DB_PASSWORD: "password"
      DB_PORT: "27017"
      DB_DRIVER: "mongodb"
    ports:
      - "5000:5000"
    expose:
      - "5000"
    depends_on:
      - mongodb
    volumes:
      - ../api:/app

  web:
    image: mfl-assistant_web:local
    build:
      context: ../web
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ../web:/app
      - /app/node_modules
    command: npm start
    environment:
       - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    expose:
      - "3000"

  smtp:
    image: reachfive/fake-smtp-server
    ports:
      - "1025:1025"
      - "1080:1080"

networks:
  default:
    name: mfl-assistant