version: "3.8"
name: mfl-assistant_dev

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mfl-assistant
    volumes:
      - ../.docker-data/mongodb:/data/db:Z
    ports:
      - "27017:27017"
    expose:
      - "27017"

  smtp:
    image: reachfive/fake-smtp-server
    container_name: smtp
    ports:
      - "1025:1025"
      - "1080:1080"

  api:
    image: mfl-assistant_api:local
    container_name: api
    build:
      context: ../api
      dockerfile: Dockerfile
    environment:
      DB_HOSTNAME: "mongodb"
      DB_NAME: "mfl-assistant"
      DB_USERNAME: "root"
      DB_PASSWORD: "password"
      DB_PORT: "27017"
      DB_DRIVER: "mongodb"
      MAIL_SERVER: "smtp"
      MAIL_STARTTLS: false
      MAIL_SSL_TLS: false
      MAIL_USE_CREDENTIALS: false
      MAIL_VALIDATE_CERTS: false
    ports:
      - "5000:5000"
    expose:
      - "5000"
    depends_on:
      - mongodb
      - smtp
    volumes:
      - ../api:/app

  web:
    image: mfl-assistant_web:local
    container_name: web
    build:
      context: ../web
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ../web:/app
      - /app/node_modules
    command: npm start
    environment:
       - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    expose:
      - "3000"

  webcoach:
    image: mfl-coach_web:local
    container_name: mfl-coach
    build:
      context: ../web-coach
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ../web-coach:/app
      - /app/node_modules
    command: npm start
    environment:
       - CHOKIDAR_USEPOLLING=true
    ports:
      - "3001:3000"
    expose:
      - "3001"

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=matomo
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ../.docker-data/mariadb:/var/lib/mysql:Z
    env_file:
      - ./mariadb.env

  matomo:
    image: matomo
    container_name: matomo
    restart: always
    environment:
      - MATOMO_DATABASE_HOST=mariadb
    env_file:
      - ./mariadb.env
    ports:
      - "8080:80"
    depends_on:
      - mariadb

networks:
  default:
    name: mfl-assistant